apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/wayloncoffee/next-iam
    newTag: latest # Image Updater 会自动改这里
