name: Build & Push next-iam to GHCR

on:
  push:
    branches: [main]
    paths:
      - "next-iam/**"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/next-iam

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: owner lowercase
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 关键：metadata-action 产出 tags / labels
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/next-iam
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./next-iam
          file: ./next-iam/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # ← 就用这里的
          labels: ${{ steps.meta.outputs.labels }} # 可选
          # 使用 sqlx 离线，请确保仓库中有 .sqlx/ 并在 Dockerfile 里 COPY 进去
          build-args: |
            SQLX_OFFLINE=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: |
          echo "images=ghcr.io/${{ env.OWNER_LC }}/next-iam"
          echo "tags=${{ steps.meta.outputs.tags }}"
